<?xml version="1.0" encoding="utf-8"?><Database Name="magentatraders" Class="LocalDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=magentatraders;Integrated Security=True" SettingsObjectName="UploadStockPrices.Properties.Settings" SettingsPropertyName="magentatradersConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MstSymbol" Member="LocalMstSymbols">
    <Type Name="LocalMstSymbol">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Symbol" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Exchange" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MstSymbol_TrnStockPrice" Member="LocalTrnStockPrices" ThisKey="Id" OtherKey="SymbolId" Type="LocalTrnStockPrice" />
    </Type>
  </Table>
  <Table Name="dbo.TrnStockPrice" Member="LocalTrnStockPrices">
    <Type Name="LocalTrnStockPrice">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SymbolId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Symbol" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QuoteDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="OpenPrice" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Column Name="HighPrice" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Column Name="LowPrice" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Column Name="ClosePrice" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Association Name="MstSymbol_TrnStockPrice" Member="LocalMstSymbol" ThisKey="SymbolId" OtherKey="Id" Type="LocalMstSymbol" IsForeignKey="true" />
    </Type>
  </Table>
</Database>