#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadStockPrices
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="magentatraders_prod")]
	public partial class ProdDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertProdMstUser(ProdMstUser instance);
    partial void UpdateProdMstUser(ProdMstUser instance);
    partial void DeleteProdMstUser(ProdMstUser instance);
    partial void InsertProdTrnStockPrice(ProdTrnStockPrice instance);
    partial void UpdateProdTrnStockPrice(ProdTrnStockPrice instance);
    partial void DeleteProdTrnStockPrice(ProdTrnStockPrice instance);
    partial void InsertProdTrnUserAlertSymbol(ProdTrnUserAlertSymbol instance);
    partial void UpdateProdTrnUserAlertSymbol(ProdTrnUserAlertSymbol instance);
    partial void DeleteProdTrnUserAlertSymbol(ProdTrnUserAlertSymbol instance);
    partial void InsertProdTrnUserAlert(ProdTrnUserAlert instance);
    partial void UpdateProdTrnUserAlert(ProdTrnUserAlert instance);
    partial void DeleteProdTrnUserAlert(ProdTrnUserAlert instance);
    partial void InsertProdMstSymbol(ProdMstSymbol instance);
    partial void UpdateProdMstSymbol(ProdMstSymbol instance);
    partial void DeleteProdMstSymbol(ProdMstSymbol instance);
    #endregion
		
		public ProdDBDataContext() : 
				base(global::UploadStockPrices.Properties.Settings.Default.magentatraders_prodConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProdDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProdDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ProdMstUser> ProdMstUsers
		{
			get
			{
				return this.GetTable<ProdMstUser>();
			}
		}
		
		public System.Data.Linq.Table<ProdTrnStockPrice> ProdTrnStockPrices
		{
			get
			{
				return this.GetTable<ProdTrnStockPrice>();
			}
		}
		
		public System.Data.Linq.Table<ProdTrnUserAlertSymbol> ProdTrnUserAlertSymbols
		{
			get
			{
				return this.GetTable<ProdTrnUserAlertSymbol>();
			}
		}
		
		public System.Data.Linq.Table<ProdTrnUserAlert> ProdTrnUserAlerts
		{
			get
			{
				return this.GetTable<ProdTrnUserAlert>();
			}
		}
		
		public System.Data.Linq.Table<ProdMstSymbol> ProdMstSymbols
		{
			get
			{
				return this.GetTable<ProdMstSymbol>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MstUser")]
	public partial class ProdMstUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _EmailAddress;
		
		private string _PhoneNumber;
		
		private string _AspNetUserId;
		
		private EntitySet<ProdTrnUserAlert> _ProdTrnUserAlerts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnAspNetUserIdChanging(string value);
    partial void OnAspNetUserIdChanged();
    #endregion
		
		public ProdMstUser()
		{
			this._ProdTrnUserAlerts = new EntitySet<ProdTrnUserAlert>(new Action<ProdTrnUserAlert>(this.attach_ProdTrnUserAlerts), new Action<ProdTrnUserAlert>(this.detach_ProdTrnUserAlerts));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AspNetUserId", DbType="NVarChar(128)")]
		public string AspNetUserId
		{
			get
			{
				return this._AspNetUserId;
			}
			set
			{
				if ((this._AspNetUserId != value))
				{
					this.OnAspNetUserIdChanging(value);
					this.SendPropertyChanging();
					this._AspNetUserId = value;
					this.SendPropertyChanged("AspNetUserId");
					this.OnAspNetUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProdMstUser_ProdTrnUserAlert", Storage="_ProdTrnUserAlerts", ThisKey="Id", OtherKey="UserId")]
		public EntitySet<ProdTrnUserAlert> ProdTrnUserAlerts
		{
			get
			{
				return this._ProdTrnUserAlerts;
			}
			set
			{
				this._ProdTrnUserAlerts.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProdTrnUserAlerts(ProdTrnUserAlert entity)
		{
			this.SendPropertyChanging();
			entity.ProdMstUser = this;
		}
		
		private void detach_ProdTrnUserAlerts(ProdTrnUserAlert entity)
		{
			this.SendPropertyChanging();
			entity.ProdMstUser = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnStockPrice")]
	public partial class ProdTrnStockPrice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _SymbolId;
		
		private string _Symbol;
		
		private System.DateTime _QuoteDate;
		
		private decimal _OpenPrice;
		
		private decimal _HighPrice;
		
		private decimal _LowPrice;
		
		private decimal _ClosePrice;
		
		private decimal _Volume;
		
		private EntityRef<ProdMstSymbol> _ProdMstSymbol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSymbolIdChanging(int value);
    partial void OnSymbolIdChanged();
    partial void OnSymbolChanging(string value);
    partial void OnSymbolChanged();
    partial void OnQuoteDateChanging(System.DateTime value);
    partial void OnQuoteDateChanged();
    partial void OnOpenPriceChanging(decimal value);
    partial void OnOpenPriceChanged();
    partial void OnHighPriceChanging(decimal value);
    partial void OnHighPriceChanged();
    partial void OnLowPriceChanging(decimal value);
    partial void OnLowPriceChanged();
    partial void OnClosePriceChanging(decimal value);
    partial void OnClosePriceChanged();
    partial void OnVolumeChanging(decimal value);
    partial void OnVolumeChanged();
    #endregion
		
		public ProdTrnStockPrice()
		{
			this._ProdMstSymbol = default(EntityRef<ProdMstSymbol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SymbolId", DbType="Int NOT NULL")]
		public int SymbolId
		{
			get
			{
				return this._SymbolId;
			}
			set
			{
				if ((this._SymbolId != value))
				{
					if (this._ProdMstSymbol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSymbolIdChanging(value);
					this.SendPropertyChanging();
					this._SymbolId = value;
					this.SendPropertyChanged("SymbolId");
					this.OnSymbolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuoteDate", DbType="DateTime NOT NULL")]
		public System.DateTime QuoteDate
		{
			get
			{
				return this._QuoteDate;
			}
			set
			{
				if ((this._QuoteDate != value))
				{
					this.OnQuoteDateChanging(value);
					this.SendPropertyChanging();
					this._QuoteDate = value;
					this.SendPropertyChanged("QuoteDate");
					this.OnQuoteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenPrice", DbType="Decimal(18,8) NOT NULL")]
		public decimal OpenPrice
		{
			get
			{
				return this._OpenPrice;
			}
			set
			{
				if ((this._OpenPrice != value))
				{
					this.OnOpenPriceChanging(value);
					this.SendPropertyChanging();
					this._OpenPrice = value;
					this.SendPropertyChanged("OpenPrice");
					this.OnOpenPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighPrice", DbType="Decimal(18,8) NOT NULL")]
		public decimal HighPrice
		{
			get
			{
				return this._HighPrice;
			}
			set
			{
				if ((this._HighPrice != value))
				{
					this.OnHighPriceChanging(value);
					this.SendPropertyChanging();
					this._HighPrice = value;
					this.SendPropertyChanged("HighPrice");
					this.OnHighPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LowPrice", DbType="Decimal(18,8) NOT NULL")]
		public decimal LowPrice
		{
			get
			{
				return this._LowPrice;
			}
			set
			{
				if ((this._LowPrice != value))
				{
					this.OnLowPriceChanging(value);
					this.SendPropertyChanging();
					this._LowPrice = value;
					this.SendPropertyChanged("LowPrice");
					this.OnLowPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosePrice", DbType="Decimal(18,8) NOT NULL")]
		public decimal ClosePrice
		{
			get
			{
				return this._ClosePrice;
			}
			set
			{
				if ((this._ClosePrice != value))
				{
					this.OnClosePriceChanging(value);
					this.SendPropertyChanging();
					this._ClosePrice = value;
					this.SendPropertyChanged("ClosePrice");
					this.OnClosePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,8) NOT NULL")]
		public decimal Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstSymbol_ProdTrnStockPrice", Storage="_ProdMstSymbol", ThisKey="SymbolId", OtherKey="Id", IsForeignKey=true)]
		public ProdMstSymbol ProdMstSymbol
		{
			get
			{
				return this._ProdMstSymbol.Entity;
			}
			set
			{
				ProdMstSymbol previousValue = this._ProdMstSymbol.Entity;
				if (((previousValue != value) 
							|| (this._ProdMstSymbol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProdMstSymbol.Entity = null;
						previousValue.ProdTrnStockPrices.Remove(this);
					}
					this._ProdMstSymbol.Entity = value;
					if ((value != null))
					{
						value.ProdTrnStockPrices.Add(this);
						this._SymbolId = value.Id;
					}
					else
					{
						this._SymbolId = default(int);
					}
					this.SendPropertyChanged("ProdMstSymbol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnUserAlertSymbols")]
	public partial class ProdTrnUserAlertSymbol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserAlertId;
		
		private int _SymbolId;
		
		private string _Symbol;
		
		private string _Trend;
		
		private System.DateTime _EncodedDate;
		
		private EntityRef<ProdTrnUserAlert> _ProdTrnUserAlert;
		
		private EntityRef<ProdMstSymbol> _ProdMstSymbol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserAlertIdChanging(int value);
    partial void OnUserAlertIdChanged();
    partial void OnSymbolIdChanging(int value);
    partial void OnSymbolIdChanged();
    partial void OnSymbolChanging(string value);
    partial void OnSymbolChanged();
    partial void OnTrendChanging(string value);
    partial void OnTrendChanged();
    partial void OnEncodedDateChanging(System.DateTime value);
    partial void OnEncodedDateChanged();
    #endregion
		
		public ProdTrnUserAlertSymbol()
		{
			this._ProdTrnUserAlert = default(EntityRef<ProdTrnUserAlert>);
			this._ProdMstSymbol = default(EntityRef<ProdMstSymbol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAlertId", DbType="Int NOT NULL")]
		public int UserAlertId
		{
			get
			{
				return this._UserAlertId;
			}
			set
			{
				if ((this._UserAlertId != value))
				{
					if (this._ProdTrnUserAlert.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserAlertIdChanging(value);
					this.SendPropertyChanging();
					this._UserAlertId = value;
					this.SendPropertyChanged("UserAlertId");
					this.OnUserAlertIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SymbolId", DbType="Int NOT NULL")]
		public int SymbolId
		{
			get
			{
				return this._SymbolId;
			}
			set
			{
				if ((this._SymbolId != value))
				{
					if (this._ProdMstSymbol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSymbolIdChanging(value);
					this.SendPropertyChanging();
					this._SymbolId = value;
					this.SendPropertyChanged("SymbolId");
					this.OnSymbolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trend", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Trend
		{
			get
			{
				return this._Trend;
			}
			set
			{
				if ((this._Trend != value))
				{
					this.OnTrendChanging(value);
					this.SendPropertyChanging();
					this._Trend = value;
					this.SendPropertyChanged("Trend");
					this.OnTrendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncodedDate", DbType="DateTime NOT NULL")]
		public System.DateTime EncodedDate
		{
			get
			{
				return this._EncodedDate;
			}
			set
			{
				if ((this._EncodedDate != value))
				{
					this.OnEncodedDateChanging(value);
					this.SendPropertyChanging();
					this._EncodedDate = value;
					this.SendPropertyChanged("EncodedDate");
					this.OnEncodedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProdTrnUserAlert_ProdTrnUserAlertSymbol", Storage="_ProdTrnUserAlert", ThisKey="UserAlertId", OtherKey="Id", IsForeignKey=true)]
		public ProdTrnUserAlert ProdTrnUserAlert
		{
			get
			{
				return this._ProdTrnUserAlert.Entity;
			}
			set
			{
				ProdTrnUserAlert previousValue = this._ProdTrnUserAlert.Entity;
				if (((previousValue != value) 
							|| (this._ProdTrnUserAlert.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProdTrnUserAlert.Entity = null;
						previousValue.ProdTrnUserAlertSymbols.Remove(this);
					}
					this._ProdTrnUserAlert.Entity = value;
					if ((value != null))
					{
						value.ProdTrnUserAlertSymbols.Add(this);
						this._UserAlertId = value.Id;
					}
					else
					{
						this._UserAlertId = default(int);
					}
					this.SendPropertyChanged("ProdTrnUserAlert");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstSymbol_ProdTrnUserAlertSymbol", Storage="_ProdMstSymbol", ThisKey="SymbolId", OtherKey="Id", IsForeignKey=true)]
		public ProdMstSymbol ProdMstSymbol
		{
			get
			{
				return this._ProdMstSymbol.Entity;
			}
			set
			{
				ProdMstSymbol previousValue = this._ProdMstSymbol.Entity;
				if (((previousValue != value) 
							|| (this._ProdMstSymbol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProdMstSymbol.Entity = null;
						previousValue.ProdTrnUserAlertSymbols.Remove(this);
					}
					this._ProdMstSymbol.Entity = value;
					if ((value != null))
					{
						value.ProdTrnUserAlertSymbols.Add(this);
						this._SymbolId = value.Id;
					}
					else
					{
						this._SymbolId = default(int);
					}
					this.SendPropertyChanged("ProdMstSymbol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrnUserAlert")]
	public partial class ProdTrnUserAlert : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _UserId;
		
		private string _Description;
		
		private string _Strategy;
		
		private bool _IsActive;
		
		private System.DateTime _EncodedDate;
		
		private string _AlertVia;
		
		private bool _SymbolFilter;
		
		private string _SymbolExchange;
		
		private System.Nullable<int> _SymbolUserFavoritesId;
		
		private decimal _StrategyGrowthDecayRate;
		
		private string _StrategyGrowthDecayTime;
		
		private bool _StrategyFilter;
		
		private bool _MACDFilter;
		
		private string _MACDCrossover;
		
		private string _MACDEMA;
		
		private bool _MagentaChannelFilter;
		
		private string _MagentaChannelBegins;
		
		private decimal _MagentaChannelAGRADR;
		
		private bool _SeasonalityFilter;
		
		private decimal _SeasonalityWinLossPercent;
		
		private decimal _SeasonalityGainLossPercent;
		
		private bool _AdditionalFilter;
		
		private decimal _AdditionalFilterPrice;
		
		private decimal _AdditionalFilterVolume;
		
		private int _AdditionalFilterNoOfYears;
		
		private int _MagentaChannelDays;
		
		private int _MagentaChannelCorrelation30;
		
		private EntitySet<ProdTrnUserAlertSymbol> _ProdTrnUserAlertSymbols;
		
		private EntityRef<ProdMstUser> _ProdMstUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnStrategyChanging(string value);
    partial void OnStrategyChanged();
    partial void OnIsActiveChanging(bool value);
    partial void OnIsActiveChanged();
    partial void OnEncodedDateChanging(System.DateTime value);
    partial void OnEncodedDateChanged();
    partial void OnAlertViaChanging(string value);
    partial void OnAlertViaChanged();
    partial void OnSymbolFilterChanging(bool value);
    partial void OnSymbolFilterChanged();
    partial void OnSymbolExchangeChanging(string value);
    partial void OnSymbolExchangeChanged();
    partial void OnSymbolUserFavoritesIdChanging(System.Nullable<int> value);
    partial void OnSymbolUserFavoritesIdChanged();
    partial void OnStrategyGrowthDecayRateChanging(decimal value);
    partial void OnStrategyGrowthDecayRateChanged();
    partial void OnStrategyGrowthDecayTimeChanging(string value);
    partial void OnStrategyGrowthDecayTimeChanged();
    partial void OnStrategyFilterChanging(bool value);
    partial void OnStrategyFilterChanged();
    partial void OnMACDFilterChanging(bool value);
    partial void OnMACDFilterChanged();
    partial void OnMACDCrossoverChanging(string value);
    partial void OnMACDCrossoverChanged();
    partial void OnMACDEMAChanging(string value);
    partial void OnMACDEMAChanged();
    partial void OnMagentaChannelFilterChanging(bool value);
    partial void OnMagentaChannelFilterChanged();
    partial void OnMagentaChannelBeginsChanging(string value);
    partial void OnMagentaChannelBeginsChanged();
    partial void OnMagentaChannelAGRADRChanging(decimal value);
    partial void OnMagentaChannelAGRADRChanged();
    partial void OnSeasonalityFilterChanging(bool value);
    partial void OnSeasonalityFilterChanged();
    partial void OnSeasonalityWinLossPercentChanging(decimal value);
    partial void OnSeasonalityWinLossPercentChanged();
    partial void OnSeasonalityGainLossPercentChanging(decimal value);
    partial void OnSeasonalityGainLossPercentChanged();
    partial void OnAdditionalFilterChanging(bool value);
    partial void OnAdditionalFilterChanged();
    partial void OnAdditionalFilterPriceChanging(decimal value);
    partial void OnAdditionalFilterPriceChanged();
    partial void OnAdditionalFilterVolumeChanging(decimal value);
    partial void OnAdditionalFilterVolumeChanged();
    partial void OnAdditionalFilterNoOfYearsChanging(int value);
    partial void OnAdditionalFilterNoOfYearsChanged();
    partial void OnMagentaChannelDaysChanging(int value);
    partial void OnMagentaChannelDaysChanged();
    partial void OnMagentaChannelCorrelation30Changing(int value);
    partial void OnMagentaChannelCorrelation30Changed();
    #endregion
		
		public ProdTrnUserAlert()
		{
			this._ProdTrnUserAlertSymbols = new EntitySet<ProdTrnUserAlertSymbol>(new Action<ProdTrnUserAlertSymbol>(this.attach_ProdTrnUserAlertSymbols), new Action<ProdTrnUserAlertSymbol>(this.detach_ProdTrnUserAlertSymbols));
			this._ProdMstUser = default(EntityRef<ProdMstUser>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._ProdMstUser.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Strategy", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Strategy
		{
			get
			{
				return this._Strategy;
			}
			set
			{
				if ((this._Strategy != value))
				{
					this.OnStrategyChanging(value);
					this.SendPropertyChanging();
					this._Strategy = value;
					this.SendPropertyChanged("Strategy");
					this.OnStrategyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EncodedDate", DbType="DateTime NOT NULL")]
		public System.DateTime EncodedDate
		{
			get
			{
				return this._EncodedDate;
			}
			set
			{
				if ((this._EncodedDate != value))
				{
					this.OnEncodedDateChanging(value);
					this.SendPropertyChanging();
					this._EncodedDate = value;
					this.SendPropertyChanged("EncodedDate");
					this.OnEncodedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertVia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AlertVia
		{
			get
			{
				return this._AlertVia;
			}
			set
			{
				if ((this._AlertVia != value))
				{
					this.OnAlertViaChanging(value);
					this.SendPropertyChanging();
					this._AlertVia = value;
					this.SendPropertyChanged("AlertVia");
					this.OnAlertViaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SymbolFilter", DbType="Bit NOT NULL")]
		public bool SymbolFilter
		{
			get
			{
				return this._SymbolFilter;
			}
			set
			{
				if ((this._SymbolFilter != value))
				{
					this.OnSymbolFilterChanging(value);
					this.SendPropertyChanging();
					this._SymbolFilter = value;
					this.SendPropertyChanged("SymbolFilter");
					this.OnSymbolFilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SymbolExchange", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SymbolExchange
		{
			get
			{
				return this._SymbolExchange;
			}
			set
			{
				if ((this._SymbolExchange != value))
				{
					this.OnSymbolExchangeChanging(value);
					this.SendPropertyChanging();
					this._SymbolExchange = value;
					this.SendPropertyChanged("SymbolExchange");
					this.OnSymbolExchangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SymbolUserFavoritesId", DbType="Int")]
		public System.Nullable<int> SymbolUserFavoritesId
		{
			get
			{
				return this._SymbolUserFavoritesId;
			}
			set
			{
				if ((this._SymbolUserFavoritesId != value))
				{
					this.OnSymbolUserFavoritesIdChanging(value);
					this.SendPropertyChanging();
					this._SymbolUserFavoritesId = value;
					this.SendPropertyChanged("SymbolUserFavoritesId");
					this.OnSymbolUserFavoritesIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrategyGrowthDecayRate", DbType="Decimal(18,5) NOT NULL")]
		public decimal StrategyGrowthDecayRate
		{
			get
			{
				return this._StrategyGrowthDecayRate;
			}
			set
			{
				if ((this._StrategyGrowthDecayRate != value))
				{
					this.OnStrategyGrowthDecayRateChanging(value);
					this.SendPropertyChanging();
					this._StrategyGrowthDecayRate = value;
					this.SendPropertyChanged("StrategyGrowthDecayRate");
					this.OnStrategyGrowthDecayRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrategyGrowthDecayTime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StrategyGrowthDecayTime
		{
			get
			{
				return this._StrategyGrowthDecayTime;
			}
			set
			{
				if ((this._StrategyGrowthDecayTime != value))
				{
					this.OnStrategyGrowthDecayTimeChanging(value);
					this.SendPropertyChanging();
					this._StrategyGrowthDecayTime = value;
					this.SendPropertyChanged("StrategyGrowthDecayTime");
					this.OnStrategyGrowthDecayTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrategyFilter", DbType="Bit NOT NULL")]
		public bool StrategyFilter
		{
			get
			{
				return this._StrategyFilter;
			}
			set
			{
				if ((this._StrategyFilter != value))
				{
					this.OnStrategyFilterChanging(value);
					this.SendPropertyChanging();
					this._StrategyFilter = value;
					this.SendPropertyChanged("StrategyFilter");
					this.OnStrategyFilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACDFilter", DbType="Bit NOT NULL")]
		public bool MACDFilter
		{
			get
			{
				return this._MACDFilter;
			}
			set
			{
				if ((this._MACDFilter != value))
				{
					this.OnMACDFilterChanging(value);
					this.SendPropertyChanging();
					this._MACDFilter = value;
					this.SendPropertyChanged("MACDFilter");
					this.OnMACDFilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACDCrossover", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MACDCrossover
		{
			get
			{
				return this._MACDCrossover;
			}
			set
			{
				if ((this._MACDCrossover != value))
				{
					this.OnMACDCrossoverChanging(value);
					this.SendPropertyChanging();
					this._MACDCrossover = value;
					this.SendPropertyChanged("MACDCrossover");
					this.OnMACDCrossoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACDEMA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MACDEMA
		{
			get
			{
				return this._MACDEMA;
			}
			set
			{
				if ((this._MACDEMA != value))
				{
					this.OnMACDEMAChanging(value);
					this.SendPropertyChanging();
					this._MACDEMA = value;
					this.SendPropertyChanged("MACDEMA");
					this.OnMACDEMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MagentaChannelFilter", DbType="Bit NOT NULL")]
		public bool MagentaChannelFilter
		{
			get
			{
				return this._MagentaChannelFilter;
			}
			set
			{
				if ((this._MagentaChannelFilter != value))
				{
					this.OnMagentaChannelFilterChanging(value);
					this.SendPropertyChanging();
					this._MagentaChannelFilter = value;
					this.SendPropertyChanged("MagentaChannelFilter");
					this.OnMagentaChannelFilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MagentaChannelBegins", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MagentaChannelBegins
		{
			get
			{
				return this._MagentaChannelBegins;
			}
			set
			{
				if ((this._MagentaChannelBegins != value))
				{
					this.OnMagentaChannelBeginsChanging(value);
					this.SendPropertyChanging();
					this._MagentaChannelBegins = value;
					this.SendPropertyChanged("MagentaChannelBegins");
					this.OnMagentaChannelBeginsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MagentaChannelAGRADR", DbType="Decimal(18,5) NOT NULL")]
		public decimal MagentaChannelAGRADR
		{
			get
			{
				return this._MagentaChannelAGRADR;
			}
			set
			{
				if ((this._MagentaChannelAGRADR != value))
				{
					this.OnMagentaChannelAGRADRChanging(value);
					this.SendPropertyChanging();
					this._MagentaChannelAGRADR = value;
					this.SendPropertyChanged("MagentaChannelAGRADR");
					this.OnMagentaChannelAGRADRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonalityFilter", DbType="Bit NOT NULL")]
		public bool SeasonalityFilter
		{
			get
			{
				return this._SeasonalityFilter;
			}
			set
			{
				if ((this._SeasonalityFilter != value))
				{
					this.OnSeasonalityFilterChanging(value);
					this.SendPropertyChanging();
					this._SeasonalityFilter = value;
					this.SendPropertyChanged("SeasonalityFilter");
					this.OnSeasonalityFilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonalityWinLossPercent", DbType="Decimal(18,5) NOT NULL")]
		public decimal SeasonalityWinLossPercent
		{
			get
			{
				return this._SeasonalityWinLossPercent;
			}
			set
			{
				if ((this._SeasonalityWinLossPercent != value))
				{
					this.OnSeasonalityWinLossPercentChanging(value);
					this.SendPropertyChanging();
					this._SeasonalityWinLossPercent = value;
					this.SendPropertyChanged("SeasonalityWinLossPercent");
					this.OnSeasonalityWinLossPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonalityGainLossPercent", DbType="Decimal(18,5) NOT NULL")]
		public decimal SeasonalityGainLossPercent
		{
			get
			{
				return this._SeasonalityGainLossPercent;
			}
			set
			{
				if ((this._SeasonalityGainLossPercent != value))
				{
					this.OnSeasonalityGainLossPercentChanging(value);
					this.SendPropertyChanging();
					this._SeasonalityGainLossPercent = value;
					this.SendPropertyChanged("SeasonalityGainLossPercent");
					this.OnSeasonalityGainLossPercentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalFilter", DbType="Bit NOT NULL")]
		public bool AdditionalFilter
		{
			get
			{
				return this._AdditionalFilter;
			}
			set
			{
				if ((this._AdditionalFilter != value))
				{
					this.OnAdditionalFilterChanging(value);
					this.SendPropertyChanging();
					this._AdditionalFilter = value;
					this.SendPropertyChanged("AdditionalFilter");
					this.OnAdditionalFilterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalFilterPrice", DbType="Decimal(18,5) NOT NULL")]
		public decimal AdditionalFilterPrice
		{
			get
			{
				return this._AdditionalFilterPrice;
			}
			set
			{
				if ((this._AdditionalFilterPrice != value))
				{
					this.OnAdditionalFilterPriceChanging(value);
					this.SendPropertyChanging();
					this._AdditionalFilterPrice = value;
					this.SendPropertyChanged("AdditionalFilterPrice");
					this.OnAdditionalFilterPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalFilterVolume", DbType="Decimal(18,5) NOT NULL")]
		public decimal AdditionalFilterVolume
		{
			get
			{
				return this._AdditionalFilterVolume;
			}
			set
			{
				if ((this._AdditionalFilterVolume != value))
				{
					this.OnAdditionalFilterVolumeChanging(value);
					this.SendPropertyChanging();
					this._AdditionalFilterVolume = value;
					this.SendPropertyChanged("AdditionalFilterVolume");
					this.OnAdditionalFilterVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalFilterNoOfYears", DbType="Int NOT NULL")]
		public int AdditionalFilterNoOfYears
		{
			get
			{
				return this._AdditionalFilterNoOfYears;
			}
			set
			{
				if ((this._AdditionalFilterNoOfYears != value))
				{
					this.OnAdditionalFilterNoOfYearsChanging(value);
					this.SendPropertyChanging();
					this._AdditionalFilterNoOfYears = value;
					this.SendPropertyChanged("AdditionalFilterNoOfYears");
					this.OnAdditionalFilterNoOfYearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MagentaChannelDays", DbType="Int NOT NULL")]
		public int MagentaChannelDays
		{
			get
			{
				return this._MagentaChannelDays;
			}
			set
			{
				if ((this._MagentaChannelDays != value))
				{
					this.OnMagentaChannelDaysChanging(value);
					this.SendPropertyChanging();
					this._MagentaChannelDays = value;
					this.SendPropertyChanged("MagentaChannelDays");
					this.OnMagentaChannelDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MagentaChannelCorrelation30", DbType="Int NOT NULL")]
		public int MagentaChannelCorrelation30
		{
			get
			{
				return this._MagentaChannelCorrelation30;
			}
			set
			{
				if ((this._MagentaChannelCorrelation30 != value))
				{
					this.OnMagentaChannelCorrelation30Changing(value);
					this.SendPropertyChanging();
					this._MagentaChannelCorrelation30 = value;
					this.SendPropertyChanged("MagentaChannelCorrelation30");
					this.OnMagentaChannelCorrelation30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProdTrnUserAlert_ProdTrnUserAlertSymbol", Storage="_ProdTrnUserAlertSymbols", ThisKey="Id", OtherKey="UserAlertId")]
		public EntitySet<ProdTrnUserAlertSymbol> ProdTrnUserAlertSymbols
		{
			get
			{
				return this._ProdTrnUserAlertSymbols;
			}
			set
			{
				this._ProdTrnUserAlertSymbols.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ProdMstUser_ProdTrnUserAlert", Storage="_ProdMstUser", ThisKey="UserId", OtherKey="Id", IsForeignKey=true)]
		public ProdMstUser ProdMstUser
		{
			get
			{
				return this._ProdMstUser.Entity;
			}
			set
			{
				ProdMstUser previousValue = this._ProdMstUser.Entity;
				if (((previousValue != value) 
							|| (this._ProdMstUser.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ProdMstUser.Entity = null;
						previousValue.ProdTrnUserAlerts.Remove(this);
					}
					this._ProdMstUser.Entity = value;
					if ((value != null))
					{
						value.ProdTrnUserAlerts.Add(this);
						this._UserId = value.Id;
					}
					else
					{
						this._UserId = default(int);
					}
					this.SendPropertyChanged("ProdMstUser");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProdTrnUserAlertSymbols(ProdTrnUserAlertSymbol entity)
		{
			this.SendPropertyChanging();
			entity.ProdTrnUserAlert = this;
		}
		
		private void detach_ProdTrnUserAlertSymbols(ProdTrnUserAlertSymbol entity)
		{
			this.SendPropertyChanging();
			entity.ProdTrnUserAlert = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MstSymbol")]
	public partial class ProdMstSymbol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Symbol;
		
		private string _Description;
		
		private string _Exchange;
		
		private System.Nullable<System.DateTime> _LatestQuoteDate;
		
		private System.Nullable<System.DateTime> _CalendarUpDate;
		
		private string _CalendarUpParticulars;
		
		private System.Nullable<decimal> _CalendarUpDelta;
		
		private System.Nullable<decimal> _CalendarUpPercentage;
		
		private System.Nullable<System.DateTime> _CalendarDownDate;
		
		private string _CalendarDownParticulars;
		
		private System.Nullable<decimal> _CalendarDownDelta;
		
		private System.Nullable<decimal> _CalendarDownPercentage;
		
		private System.Nullable<decimal> _ClosePrice;
		
		private System.Nullable<decimal> _Volume;
		
		private System.Nullable<decimal> _GrowthDecayRate;
		
		private System.Nullable<decimal> _GrowthDecayRateW1;
		
		private System.Nullable<decimal> _GrowthDecayRateW2;
		
		private System.Nullable<decimal> _GrowthDecayRateW3;
		
		private System.Nullable<decimal> _GrowthDecayRateM1;
		
		private System.Nullable<decimal> _GrowthDecayRateM2;
		
		private System.Nullable<decimal> _GrowthDecayRateM3;
		
		private System.Nullable<int> _NoOfYears;
		
		private System.Nullable<int> _TrendNoOfDays;
		
		private string _WinLossCurrent30;
		
		private System.Nullable<decimal> _WinLossAverageCurrent30;
		
		private string _WinLoss20;
		
		private System.Nullable<decimal> _WinLossAverage20;
		
		private string _WinLoss40;
		
		private System.Nullable<decimal> _WinLossAverage40;
		
		private string _WinLoss60;
		
		private System.Nullable<decimal> _WinLossAverage60;
		
		private System.Nullable<decimal> _CorrelationCoefficient30;
		
		private System.Nullable<decimal> _SeasonalityCorrelation;
		
		private System.Nullable<int> _MACDTrendNoOfDays;
		
		private System.Nullable<decimal> _MACDGrowthDecayRate;
		
		private System.Nullable<int> _EMATrendNoOfDays;
		
		private System.Nullable<decimal> _EMAGrowthDecayRate;
		
		private System.Nullable<System.DateTime> _EMAStartDate;
		
		private System.Nullable<decimal> _EMALinear;
		
		private System.Nullable<int> _MACDLastCrossoverNoOfDays;
		
		private string _MACDPosition;
		
		private System.Nullable<int> _EMALastCrossoverNoOfDays;
		
		private System.Nullable<decimal> _Nov7ClosePrice;
		
		private System.Nullable<int> _Nov7NumberOfDays;
		
		private System.Nullable<decimal> _Nov7CorrelationCoefficient;
		
		private System.Nullable<decimal> _MACDLinear;
		
		private EntitySet<ProdTrnStockPrice> _ProdTrnStockPrices;
		
		private EntitySet<ProdTrnUserAlertSymbol> _ProdTrnUserAlertSymbols;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSymbolChanging(string value);
    partial void OnSymbolChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnExchangeChanging(string value);
    partial void OnExchangeChanged();
    partial void OnLatestQuoteDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLatestQuoteDateChanged();
    partial void OnCalendarUpDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCalendarUpDateChanged();
    partial void OnCalendarUpParticularsChanging(string value);
    partial void OnCalendarUpParticularsChanged();
    partial void OnCalendarUpDeltaChanging(System.Nullable<decimal> value);
    partial void OnCalendarUpDeltaChanged();
    partial void OnCalendarUpPercentageChanging(System.Nullable<decimal> value);
    partial void OnCalendarUpPercentageChanged();
    partial void OnCalendarDownDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCalendarDownDateChanged();
    partial void OnCalendarDownParticularsChanging(string value);
    partial void OnCalendarDownParticularsChanged();
    partial void OnCalendarDownDeltaChanging(System.Nullable<decimal> value);
    partial void OnCalendarDownDeltaChanged();
    partial void OnCalendarDownPercentageChanging(System.Nullable<decimal> value);
    partial void OnCalendarDownPercentageChanged();
    partial void OnClosePriceChanging(System.Nullable<decimal> value);
    partial void OnClosePriceChanged();
    partial void OnVolumeChanging(System.Nullable<decimal> value);
    partial void OnVolumeChanged();
    partial void OnGrowthDecayRateChanging(System.Nullable<decimal> value);
    partial void OnGrowthDecayRateChanged();
    partial void OnGrowthDecayRateW1Changing(System.Nullable<decimal> value);
    partial void OnGrowthDecayRateW1Changed();
    partial void OnGrowthDecayRateW2Changing(System.Nullable<decimal> value);
    partial void OnGrowthDecayRateW2Changed();
    partial void OnGrowthDecayRateW3Changing(System.Nullable<decimal> value);
    partial void OnGrowthDecayRateW3Changed();
    partial void OnGrowthDecayRateM1Changing(System.Nullable<decimal> value);
    partial void OnGrowthDecayRateM1Changed();
    partial void OnGrowthDecayRateM2Changing(System.Nullable<decimal> value);
    partial void OnGrowthDecayRateM2Changed();
    partial void OnGrowthDecayRateM3Changing(System.Nullable<decimal> value);
    partial void OnGrowthDecayRateM3Changed();
    partial void OnNoOfYearsChanging(System.Nullable<int> value);
    partial void OnNoOfYearsChanged();
    partial void OnTrendNoOfDaysChanging(System.Nullable<int> value);
    partial void OnTrendNoOfDaysChanged();
    partial void OnWinLossCurrent30Changing(string value);
    partial void OnWinLossCurrent30Changed();
    partial void OnWinLossAverageCurrent30Changing(System.Nullable<decimal> value);
    partial void OnWinLossAverageCurrent30Changed();
    partial void OnWinLoss20Changing(string value);
    partial void OnWinLoss20Changed();
    partial void OnWinLossAverage20Changing(System.Nullable<decimal> value);
    partial void OnWinLossAverage20Changed();
    partial void OnWinLoss40Changing(string value);
    partial void OnWinLoss40Changed();
    partial void OnWinLossAverage40Changing(System.Nullable<decimal> value);
    partial void OnWinLossAverage40Changed();
    partial void OnWinLoss60Changing(string value);
    partial void OnWinLoss60Changed();
    partial void OnWinLossAverage60Changing(System.Nullable<decimal> value);
    partial void OnWinLossAverage60Changed();
    partial void OnCorrelationCoefficient30Changing(System.Nullable<decimal> value);
    partial void OnCorrelationCoefficient30Changed();
    partial void OnSeasonalityCorrelationChanging(System.Nullable<decimal> value);
    partial void OnSeasonalityCorrelationChanged();
    partial void OnMACDTrendNoOfDaysChanging(System.Nullable<int> value);
    partial void OnMACDTrendNoOfDaysChanged();
    partial void OnMACDGrowthDecayRateChanging(System.Nullable<decimal> value);
    partial void OnMACDGrowthDecayRateChanged();
    partial void OnEMATrendNoOfDaysChanging(System.Nullable<int> value);
    partial void OnEMATrendNoOfDaysChanged();
    partial void OnEMAGrowthDecayRateChanging(System.Nullable<decimal> value);
    partial void OnEMAGrowthDecayRateChanged();
    partial void OnEMAStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEMAStartDateChanged();
    partial void OnEMALinearChanging(System.Nullable<decimal> value);
    partial void OnEMALinearChanged();
    partial void OnMACDLastCrossoverNoOfDaysChanging(System.Nullable<int> value);
    partial void OnMACDLastCrossoverNoOfDaysChanged();
    partial void OnMACDPositionChanging(string value);
    partial void OnMACDPositionChanged();
    partial void OnEMALastCrossoverNoOfDaysChanging(System.Nullable<int> value);
    partial void OnEMALastCrossoverNoOfDaysChanged();
    partial void OnNov7ClosePriceChanging(System.Nullable<decimal> value);
    partial void OnNov7ClosePriceChanged();
    partial void OnNov7NumberOfDaysChanging(System.Nullable<int> value);
    partial void OnNov7NumberOfDaysChanged();
    partial void OnNov7CorrelationCoefficientChanging(System.Nullable<decimal> value);
    partial void OnNov7CorrelationCoefficientChanged();
    partial void OnMACDLinearChanging(System.Nullable<decimal> value);
    partial void OnMACDLinearChanged();
    #endregion
		
		public ProdMstSymbol()
		{
			this._ProdTrnStockPrices = new EntitySet<ProdTrnStockPrice>(new Action<ProdTrnStockPrice>(this.attach_ProdTrnStockPrices), new Action<ProdTrnStockPrice>(this.detach_ProdTrnStockPrices));
			this._ProdTrnUserAlertSymbols = new EntitySet<ProdTrnUserAlertSymbol>(new Action<ProdTrnUserAlertSymbol>(this.attach_ProdTrnUserAlertSymbols), new Action<ProdTrnUserAlertSymbol>(this.detach_ProdTrnUserAlertSymbols));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exchange", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Exchange
		{
			get
			{
				return this._Exchange;
			}
			set
			{
				if ((this._Exchange != value))
				{
					this.OnExchangeChanging(value);
					this.SendPropertyChanging();
					this._Exchange = value;
					this.SendPropertyChanged("Exchange");
					this.OnExchangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LatestQuoteDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LatestQuoteDate
		{
			get
			{
				return this._LatestQuoteDate;
			}
			set
			{
				if ((this._LatestQuoteDate != value))
				{
					this.OnLatestQuoteDateChanging(value);
					this.SendPropertyChanging();
					this._LatestQuoteDate = value;
					this.SendPropertyChanged("LatestQuoteDate");
					this.OnLatestQuoteDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarUpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CalendarUpDate
		{
			get
			{
				return this._CalendarUpDate;
			}
			set
			{
				if ((this._CalendarUpDate != value))
				{
					this.OnCalendarUpDateChanging(value);
					this.SendPropertyChanging();
					this._CalendarUpDate = value;
					this.SendPropertyChanged("CalendarUpDate");
					this.OnCalendarUpDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarUpParticulars", DbType="NVarChar(255)")]
		public string CalendarUpParticulars
		{
			get
			{
				return this._CalendarUpParticulars;
			}
			set
			{
				if ((this._CalendarUpParticulars != value))
				{
					this.OnCalendarUpParticularsChanging(value);
					this.SendPropertyChanging();
					this._CalendarUpParticulars = value;
					this.SendPropertyChanged("CalendarUpParticulars");
					this.OnCalendarUpParticularsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarUpDelta", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> CalendarUpDelta
		{
			get
			{
				return this._CalendarUpDelta;
			}
			set
			{
				if ((this._CalendarUpDelta != value))
				{
					this.OnCalendarUpDeltaChanging(value);
					this.SendPropertyChanging();
					this._CalendarUpDelta = value;
					this.SendPropertyChanged("CalendarUpDelta");
					this.OnCalendarUpDeltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarUpPercentage", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> CalendarUpPercentage
		{
			get
			{
				return this._CalendarUpPercentage;
			}
			set
			{
				if ((this._CalendarUpPercentage != value))
				{
					this.OnCalendarUpPercentageChanging(value);
					this.SendPropertyChanging();
					this._CalendarUpPercentage = value;
					this.SendPropertyChanged("CalendarUpPercentage");
					this.OnCalendarUpPercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarDownDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CalendarDownDate
		{
			get
			{
				return this._CalendarDownDate;
			}
			set
			{
				if ((this._CalendarDownDate != value))
				{
					this.OnCalendarDownDateChanging(value);
					this.SendPropertyChanging();
					this._CalendarDownDate = value;
					this.SendPropertyChanged("CalendarDownDate");
					this.OnCalendarDownDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarDownParticulars", DbType="NVarChar(255)")]
		public string CalendarDownParticulars
		{
			get
			{
				return this._CalendarDownParticulars;
			}
			set
			{
				if ((this._CalendarDownParticulars != value))
				{
					this.OnCalendarDownParticularsChanging(value);
					this.SendPropertyChanging();
					this._CalendarDownParticulars = value;
					this.SendPropertyChanged("CalendarDownParticulars");
					this.OnCalendarDownParticularsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarDownDelta", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> CalendarDownDelta
		{
			get
			{
				return this._CalendarDownDelta;
			}
			set
			{
				if ((this._CalendarDownDelta != value))
				{
					this.OnCalendarDownDeltaChanging(value);
					this.SendPropertyChanging();
					this._CalendarDownDelta = value;
					this.SendPropertyChanged("CalendarDownDelta");
					this.OnCalendarDownDeltaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalendarDownPercentage", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> CalendarDownPercentage
		{
			get
			{
				return this._CalendarDownPercentage;
			}
			set
			{
				if ((this._CalendarDownPercentage != value))
				{
					this.OnCalendarDownPercentageChanging(value);
					this.SendPropertyChanging();
					this._CalendarDownPercentage = value;
					this.SendPropertyChanged("CalendarDownPercentage");
					this.OnCalendarDownPercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClosePrice", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> ClosePrice
		{
			get
			{
				return this._ClosePrice;
			}
			set
			{
				if ((this._ClosePrice != value))
				{
					this.OnClosePriceChanging(value);
					this.SendPropertyChanging();
					this._ClosePrice = value;
					this.SendPropertyChanged("ClosePrice");
					this.OnClosePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowthDecayRate", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> GrowthDecayRate
		{
			get
			{
				return this._GrowthDecayRate;
			}
			set
			{
				if ((this._GrowthDecayRate != value))
				{
					this.OnGrowthDecayRateChanging(value);
					this.SendPropertyChanging();
					this._GrowthDecayRate = value;
					this.SendPropertyChanged("GrowthDecayRate");
					this.OnGrowthDecayRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowthDecayRateW1", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> GrowthDecayRateW1
		{
			get
			{
				return this._GrowthDecayRateW1;
			}
			set
			{
				if ((this._GrowthDecayRateW1 != value))
				{
					this.OnGrowthDecayRateW1Changing(value);
					this.SendPropertyChanging();
					this._GrowthDecayRateW1 = value;
					this.SendPropertyChanged("GrowthDecayRateW1");
					this.OnGrowthDecayRateW1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowthDecayRateW2", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> GrowthDecayRateW2
		{
			get
			{
				return this._GrowthDecayRateW2;
			}
			set
			{
				if ((this._GrowthDecayRateW2 != value))
				{
					this.OnGrowthDecayRateW2Changing(value);
					this.SendPropertyChanging();
					this._GrowthDecayRateW2 = value;
					this.SendPropertyChanged("GrowthDecayRateW2");
					this.OnGrowthDecayRateW2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowthDecayRateW3", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> GrowthDecayRateW3
		{
			get
			{
				return this._GrowthDecayRateW3;
			}
			set
			{
				if ((this._GrowthDecayRateW3 != value))
				{
					this.OnGrowthDecayRateW3Changing(value);
					this.SendPropertyChanging();
					this._GrowthDecayRateW3 = value;
					this.SendPropertyChanged("GrowthDecayRateW3");
					this.OnGrowthDecayRateW3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowthDecayRateM1", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> GrowthDecayRateM1
		{
			get
			{
				return this._GrowthDecayRateM1;
			}
			set
			{
				if ((this._GrowthDecayRateM1 != value))
				{
					this.OnGrowthDecayRateM1Changing(value);
					this.SendPropertyChanging();
					this._GrowthDecayRateM1 = value;
					this.SendPropertyChanged("GrowthDecayRateM1");
					this.OnGrowthDecayRateM1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowthDecayRateM2", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> GrowthDecayRateM2
		{
			get
			{
				return this._GrowthDecayRateM2;
			}
			set
			{
				if ((this._GrowthDecayRateM2 != value))
				{
					this.OnGrowthDecayRateM2Changing(value);
					this.SendPropertyChanging();
					this._GrowthDecayRateM2 = value;
					this.SendPropertyChanged("GrowthDecayRateM2");
					this.OnGrowthDecayRateM2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrowthDecayRateM3", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> GrowthDecayRateM3
		{
			get
			{
				return this._GrowthDecayRateM3;
			}
			set
			{
				if ((this._GrowthDecayRateM3 != value))
				{
					this.OnGrowthDecayRateM3Changing(value);
					this.SendPropertyChanging();
					this._GrowthDecayRateM3 = value;
					this.SendPropertyChanged("GrowthDecayRateM3");
					this.OnGrowthDecayRateM3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfYears", DbType="Int")]
		public System.Nullable<int> NoOfYears
		{
			get
			{
				return this._NoOfYears;
			}
			set
			{
				if ((this._NoOfYears != value))
				{
					this.OnNoOfYearsChanging(value);
					this.SendPropertyChanging();
					this._NoOfYears = value;
					this.SendPropertyChanged("NoOfYears");
					this.OnNoOfYearsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrendNoOfDays", DbType="Int")]
		public System.Nullable<int> TrendNoOfDays
		{
			get
			{
				return this._TrendNoOfDays;
			}
			set
			{
				if ((this._TrendNoOfDays != value))
				{
					this.OnTrendNoOfDaysChanging(value);
					this.SendPropertyChanging();
					this._TrendNoOfDays = value;
					this.SendPropertyChanged("TrendNoOfDays");
					this.OnTrendNoOfDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinLossCurrent30", DbType="NVarChar(50)")]
		public string WinLossCurrent30
		{
			get
			{
				return this._WinLossCurrent30;
			}
			set
			{
				if ((this._WinLossCurrent30 != value))
				{
					this.OnWinLossCurrent30Changing(value);
					this.SendPropertyChanging();
					this._WinLossCurrent30 = value;
					this.SendPropertyChanged("WinLossCurrent30");
					this.OnWinLossCurrent30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinLossAverageCurrent30", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> WinLossAverageCurrent30
		{
			get
			{
				return this._WinLossAverageCurrent30;
			}
			set
			{
				if ((this._WinLossAverageCurrent30 != value))
				{
					this.OnWinLossAverageCurrent30Changing(value);
					this.SendPropertyChanging();
					this._WinLossAverageCurrent30 = value;
					this.SendPropertyChanged("WinLossAverageCurrent30");
					this.OnWinLossAverageCurrent30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinLoss20", DbType="NVarChar(50)")]
		public string WinLoss20
		{
			get
			{
				return this._WinLoss20;
			}
			set
			{
				if ((this._WinLoss20 != value))
				{
					this.OnWinLoss20Changing(value);
					this.SendPropertyChanging();
					this._WinLoss20 = value;
					this.SendPropertyChanged("WinLoss20");
					this.OnWinLoss20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinLossAverage20", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> WinLossAverage20
		{
			get
			{
				return this._WinLossAverage20;
			}
			set
			{
				if ((this._WinLossAverage20 != value))
				{
					this.OnWinLossAverage20Changing(value);
					this.SendPropertyChanging();
					this._WinLossAverage20 = value;
					this.SendPropertyChanged("WinLossAverage20");
					this.OnWinLossAverage20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinLoss40", DbType="NVarChar(50)")]
		public string WinLoss40
		{
			get
			{
				return this._WinLoss40;
			}
			set
			{
				if ((this._WinLoss40 != value))
				{
					this.OnWinLoss40Changing(value);
					this.SendPropertyChanging();
					this._WinLoss40 = value;
					this.SendPropertyChanged("WinLoss40");
					this.OnWinLoss40Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinLossAverage40", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> WinLossAverage40
		{
			get
			{
				return this._WinLossAverage40;
			}
			set
			{
				if ((this._WinLossAverage40 != value))
				{
					this.OnWinLossAverage40Changing(value);
					this.SendPropertyChanging();
					this._WinLossAverage40 = value;
					this.SendPropertyChanged("WinLossAverage40");
					this.OnWinLossAverage40Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinLoss60", DbType="NVarChar(50)")]
		public string WinLoss60
		{
			get
			{
				return this._WinLoss60;
			}
			set
			{
				if ((this._WinLoss60 != value))
				{
					this.OnWinLoss60Changing(value);
					this.SendPropertyChanging();
					this._WinLoss60 = value;
					this.SendPropertyChanged("WinLoss60");
					this.OnWinLoss60Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinLossAverage60", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> WinLossAverage60
		{
			get
			{
				return this._WinLossAverage60;
			}
			set
			{
				if ((this._WinLossAverage60 != value))
				{
					this.OnWinLossAverage60Changing(value);
					this.SendPropertyChanging();
					this._WinLossAverage60 = value;
					this.SendPropertyChanged("WinLossAverage60");
					this.OnWinLossAverage60Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrelationCoefficient30", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> CorrelationCoefficient30
		{
			get
			{
				return this._CorrelationCoefficient30;
			}
			set
			{
				if ((this._CorrelationCoefficient30 != value))
				{
					this.OnCorrelationCoefficient30Changing(value);
					this.SendPropertyChanging();
					this._CorrelationCoefficient30 = value;
					this.SendPropertyChanged("CorrelationCoefficient30");
					this.OnCorrelationCoefficient30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeasonalityCorrelation", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> SeasonalityCorrelation
		{
			get
			{
				return this._SeasonalityCorrelation;
			}
			set
			{
				if ((this._SeasonalityCorrelation != value))
				{
					this.OnSeasonalityCorrelationChanging(value);
					this.SendPropertyChanging();
					this._SeasonalityCorrelation = value;
					this.SendPropertyChanged("SeasonalityCorrelation");
					this.OnSeasonalityCorrelationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACDTrendNoOfDays", DbType="Int")]
		public System.Nullable<int> MACDTrendNoOfDays
		{
			get
			{
				return this._MACDTrendNoOfDays;
			}
			set
			{
				if ((this._MACDTrendNoOfDays != value))
				{
					this.OnMACDTrendNoOfDaysChanging(value);
					this.SendPropertyChanging();
					this._MACDTrendNoOfDays = value;
					this.SendPropertyChanged("MACDTrendNoOfDays");
					this.OnMACDTrendNoOfDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACDGrowthDecayRate", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> MACDGrowthDecayRate
		{
			get
			{
				return this._MACDGrowthDecayRate;
			}
			set
			{
				if ((this._MACDGrowthDecayRate != value))
				{
					this.OnMACDGrowthDecayRateChanging(value);
					this.SendPropertyChanging();
					this._MACDGrowthDecayRate = value;
					this.SendPropertyChanged("MACDGrowthDecayRate");
					this.OnMACDGrowthDecayRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMATrendNoOfDays", DbType="Int")]
		public System.Nullable<int> EMATrendNoOfDays
		{
			get
			{
				return this._EMATrendNoOfDays;
			}
			set
			{
				if ((this._EMATrendNoOfDays != value))
				{
					this.OnEMATrendNoOfDaysChanging(value);
					this.SendPropertyChanging();
					this._EMATrendNoOfDays = value;
					this.SendPropertyChanged("EMATrendNoOfDays");
					this.OnEMATrendNoOfDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAGrowthDecayRate", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> EMAGrowthDecayRate
		{
			get
			{
				return this._EMAGrowthDecayRate;
			}
			set
			{
				if ((this._EMAGrowthDecayRate != value))
				{
					this.OnEMAGrowthDecayRateChanging(value);
					this.SendPropertyChanging();
					this._EMAGrowthDecayRate = value;
					this.SendPropertyChanged("EMAGrowthDecayRate");
					this.OnEMAGrowthDecayRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAStartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EMAStartDate
		{
			get
			{
				return this._EMAStartDate;
			}
			set
			{
				if ((this._EMAStartDate != value))
				{
					this.OnEMAStartDateChanging(value);
					this.SendPropertyChanging();
					this._EMAStartDate = value;
					this.SendPropertyChanged("EMAStartDate");
					this.OnEMAStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMALinear", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> EMALinear
		{
			get
			{
				return this._EMALinear;
			}
			set
			{
				if ((this._EMALinear != value))
				{
					this.OnEMALinearChanging(value);
					this.SendPropertyChanging();
					this._EMALinear = value;
					this.SendPropertyChanged("EMALinear");
					this.OnEMALinearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACDLastCrossoverNoOfDays", DbType="Int")]
		public System.Nullable<int> MACDLastCrossoverNoOfDays
		{
			get
			{
				return this._MACDLastCrossoverNoOfDays;
			}
			set
			{
				if ((this._MACDLastCrossoverNoOfDays != value))
				{
					this.OnMACDLastCrossoverNoOfDaysChanging(value);
					this.SendPropertyChanging();
					this._MACDLastCrossoverNoOfDays = value;
					this.SendPropertyChanged("MACDLastCrossoverNoOfDays");
					this.OnMACDLastCrossoverNoOfDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACDPosition", DbType="NVarChar(50)")]
		public string MACDPosition
		{
			get
			{
				return this._MACDPosition;
			}
			set
			{
				if ((this._MACDPosition != value))
				{
					this.OnMACDPositionChanging(value);
					this.SendPropertyChanging();
					this._MACDPosition = value;
					this.SendPropertyChanged("MACDPosition");
					this.OnMACDPositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMALastCrossoverNoOfDays", DbType="Int")]
		public System.Nullable<int> EMALastCrossoverNoOfDays
		{
			get
			{
				return this._EMALastCrossoverNoOfDays;
			}
			set
			{
				if ((this._EMALastCrossoverNoOfDays != value))
				{
					this.OnEMALastCrossoverNoOfDaysChanging(value);
					this.SendPropertyChanging();
					this._EMALastCrossoverNoOfDays = value;
					this.SendPropertyChanged("EMALastCrossoverNoOfDays");
					this.OnEMALastCrossoverNoOfDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nov7ClosePrice", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> Nov7ClosePrice
		{
			get
			{
				return this._Nov7ClosePrice;
			}
			set
			{
				if ((this._Nov7ClosePrice != value))
				{
					this.OnNov7ClosePriceChanging(value);
					this.SendPropertyChanging();
					this._Nov7ClosePrice = value;
					this.SendPropertyChanged("Nov7ClosePrice");
					this.OnNov7ClosePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nov7NumberOfDays", DbType="Int")]
		public System.Nullable<int> Nov7NumberOfDays
		{
			get
			{
				return this._Nov7NumberOfDays;
			}
			set
			{
				if ((this._Nov7NumberOfDays != value))
				{
					this.OnNov7NumberOfDaysChanging(value);
					this.SendPropertyChanging();
					this._Nov7NumberOfDays = value;
					this.SendPropertyChanged("Nov7NumberOfDays");
					this.OnNov7NumberOfDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nov7CorrelationCoefficient", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> Nov7CorrelationCoefficient
		{
			get
			{
				return this._Nov7CorrelationCoefficient;
			}
			set
			{
				if ((this._Nov7CorrelationCoefficient != value))
				{
					this.OnNov7CorrelationCoefficientChanging(value);
					this.SendPropertyChanging();
					this._Nov7CorrelationCoefficient = value;
					this.SendPropertyChanged("Nov7CorrelationCoefficient");
					this.OnNov7CorrelationCoefficientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MACDLinear", DbType="Decimal(18,5)")]
		public System.Nullable<decimal> MACDLinear
		{
			get
			{
				return this._MACDLinear;
			}
			set
			{
				if ((this._MACDLinear != value))
				{
					this.OnMACDLinearChanging(value);
					this.SendPropertyChanging();
					this._MACDLinear = value;
					this.SendPropertyChanged("MACDLinear");
					this.OnMACDLinearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstSymbol_ProdTrnStockPrice", Storage="_ProdTrnStockPrices", ThisKey="Id", OtherKey="SymbolId")]
		public EntitySet<ProdTrnStockPrice> ProdTrnStockPrices
		{
			get
			{
				return this._ProdTrnStockPrices;
			}
			set
			{
				this._ProdTrnStockPrices.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MstSymbol_ProdTrnUserAlertSymbol", Storage="_ProdTrnUserAlertSymbols", ThisKey="Id", OtherKey="SymbolId")]
		public EntitySet<ProdTrnUserAlertSymbol> ProdTrnUserAlertSymbols
		{
			get
			{
				return this._ProdTrnUserAlertSymbols;
			}
			set
			{
				this._ProdTrnUserAlertSymbols.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProdTrnStockPrices(ProdTrnStockPrice entity)
		{
			this.SendPropertyChanging();
			entity.ProdMstSymbol = this;
		}
		
		private void detach_ProdTrnStockPrices(ProdTrnStockPrice entity)
		{
			this.SendPropertyChanging();
			entity.ProdMstSymbol = null;
		}
		
		private void attach_ProdTrnUserAlertSymbols(ProdTrnUserAlertSymbol entity)
		{
			this.SendPropertyChanging();
			entity.ProdMstSymbol = this;
		}
		
		private void detach_ProdTrnUserAlertSymbols(ProdTrnUserAlertSymbol entity)
		{
			this.SendPropertyChanging();
			entity.ProdMstSymbol = null;
		}
	}
}
#pragma warning restore 1591
